import "./style/style.scss"
import "./style/fonts.scss"
import "./script/fixed-header"
import "./script/up-btn"
import "./script/scrollTo"
import "./script/footerUp"
import "./script/cookieAlert"
import "./script/hiddenNav"